# Update the Streamlit script to include additional guidance, style improvements, and GitHub enhancement tips

enhanced_script_lines = [
    "import streamlit as st",
    "from datetime import datetime",
    "",
    "st.set_page_config(page_title='Cybersecurity Tracker', layout='wide')",
    "st.title('🛡️ Cybersecurity Career Tracker')",
    "st.markdown('''",
    "#### 📆 May 27 – June 26",
    "Track your daily progress toward landing a cybersecurity role:",
    "- 🎯 Apply to **200+ jobs**",
    "- 🎓 Complete **Google Cybersecurity Certificate**",
    "- 🧪 Master **10+ TryHackMe labs**",
    "- 🌐 Strengthen **GitHub & LinkedIn presence**",
    "''')",
    "",
    "# TIMER",
    "if 'start_time' not in st.session_state:",
    "    st.session_state.start_time = None",
    "",
    "if st.button('▶️ Start Timer'):",
    "    st.session_state.start_time = datetime.now()",
    "",
    "if st.session_state.start_time:",
    "    elapsed = datetime.now() - st.session_state.start_time",
    "    st.success(f'⏱️ Timer: {elapsed.seconds // 60:02d}:{elapsed.seconds % 60:02d}')",
    "",
    "st.markdown('---')",
    "st.markdown('### ✅ Daily Checklist')",
    "",
    f"tasks = {df_plan.to_dict(orient='records')}",
    "",
    "tryhackme_links = {",
    "    'Intro to SOC': 'https://tryhackme.com/room/introtosoc',",
    "    'Phishing Emails': 'https://tryhackme.com/room/phishingemails',",
    "    'Splunk 101': 'https://tryhackme.com/room/splunk101',",
    "    'Network Services 1': 'https://tryhackme.com/room/networkservices',",
    "    'Blue Team Fundamentals': 'https://tryhackme.com/room/blueteamfundamentals',",
    "    'Cyber Defense Frameworks': 'https://tryhackme.com/room/cyberdefenseframeworks',",
    "    'Threat Hunting Basics': 'https://tryhackme.com/room/threathuntingbasics',",
    "    'SOC Level 1': 'https://tryhackme.com/room/soclevel1',",
    "    'Splunk Processing': 'https://tryhackme.com/room/splunkprocessing',",
    "    'Detection Lab': 'https://tryhackme.com/room/detectionlab'",
    "}",
    "",
    "for task in tasks:",
    "    date = task['Date']",
    "    day = task['Day']",
    "    task_text = task['Tasks']",
    "    for room, link in tryhackme_links.items():",
    "        if room in task_text:",
    "            task_text = task_text.replace(room, f'[{room}]({link})')",
    "    task_text = task_text.replace('\\n', '  \\n')",
    "    key = f'{date}_{day}'.replace(' ', '_').replace(':', '').replace('-', '_')",
    "    st.checkbox(f'### {day}  \\n📅 {date}  \\n📝 {task_text}', key=key)",
    "    st.markdown('---')",
    "",
    "st.markdown('### 💡 GitHub Optimization Tips')",
    "st.markdown('''",
    "- ✅ Pin 3–6 relevant cybersecurity projects (e.g., steganography, SIEM, C-SCRM, SOC scripts)",
    "- 📝 Add a clean README with: project purpose, tools used, screenshots, and key takeaways",
    "- 🔗 Include links in your resume and LinkedIn profile",
    "- 🌟 Use GitHub topics (e.g., `cybersecurity`, `digital-forensics`, `splunk`, `SIEM`)",
    "- 🧩 Optionally, add GitHub Actions or badges for automation or test passing",
    "''')",
    "",
    "st.markdown('### 🌐 LinkedIn Quick Wins')",
    "st.markdown('''",
    "- 🪪 Use a keyword-optimized headline: 'Cybersecurity Analyst | SOC | GRC | Splunk | SIEM'",
    "- 💬 Write a 3-line summary with achievements + goals",
    "- 📢 Share your progress weekly (e.g., 'Finished Course 3 of Google Cybersecurity!')",
    "- 🤝 Connect with recruiters and alumni in security roles",
    "- 📌 Feature your GitHub, resume, and portfolio site on your profile",
    "''')"
]

# Save the script
enhanced_script = "\n".join(enhanced_script_lines)
enhanced_script_path = "/mnt/data/enhanced_streamlit_tracker.py"

with open(enhanced_script_path, "w") as f:
    f.write(enhanced_script)

enhanced_script_path
